create table if not exists images
(
    image_id       bigint generated by default as identity
        primary key,
    file_extension varchar(255) not null,
    file_path      varchar(255) not null,
    file_size      bigint       not null,
    media_type     varchar(255) not null
);

COMMENT ON TABLE images IS 'Изображения';
COMMENT ON COLUMN images.image_id IS 'Номер изображения';
COMMENT ON COLUMN images.file_extension IS 'Расширение файла';
COMMENT ON COLUMN images.file_path IS 'Путь файла';
COMMENT ON COLUMN images.file_size IS 'Размер файла';
COMMENT ON COLUMN images.media_type IS 'Тип носителя';

create table if not exists address
(
    address_id bigint generated by default as identity
        primary key,
    building   varchar(255) not null,
    city       varchar(255) not null,
    street     varchar(255) not null
);

COMMENT ON TABLE address IS 'Адрес';
COMMENT ON COLUMN address.address_id IS 'Номер адреса';
COMMENT ON COLUMN address.building IS 'Номер дома';
COMMENT ON COLUMN address.city IS 'Город';
COMMENT ON COLUMN address.street IS 'Улица';

create table if not exists couriers
(
    courier_id  bigint generated by default as identity
        primary key,
    coordinates integer     not null,
    name       varchar(20) not null,
    phone       varchar(20) not null,
    status      varchar(255)
);

COMMENT ON TABLE couriers IS 'Курьеры';
COMMENT ON COLUMN couriers.courier_id IS 'Номер курьера';
COMMENT ON COLUMN couriers.coordinates IS 'Координаты курьера';
COMMENT ON COLUMN couriers.name IS 'Имя курьера';
COMMENT ON COLUMN couriers.phone IS 'Телефон курьера';
COMMENT ON COLUMN couriers.status IS 'Статус курьера';

create table if not exists customers
(
    customer_id bigint generated by default as identity
        primary key,
    distance    integer      not null,
    name        varchar(255) not null,
    address_id  bigint
);

COMMENT ON TABLE customers IS 'Клиенты';
COMMENT ON COLUMN customers.customer_id IS 'Номер клиента';
COMMENT ON COLUMN customers.distance IS 'Дистанция до ресторана';
COMMENT ON COLUMN customers.name IS 'Имя клиента';
COMMENT ON COLUMN customers.address_id IS 'Номер адреса';

create table if not exists payments
(
    payment_id  bigint generated by default as identity
        primary key,
    amount      integer      not null,
    card_number varchar(255) not null
);

COMMENT ON TABLE payments IS 'Платежи';
COMMENT ON COLUMN payments.payment_id IS 'Номер оплаты';
COMMENT ON COLUMN payments.amount IS 'Сумма оплаты';
COMMENT ON COLUMN payments.card_number IS 'Номер карты';

create table if not exists restaurants
(
    restaurant_id bigint generated by default as identity
        primary key,
    distance      integer      not null,
    name          varchar(255) not null,
    address_id    bigint
        constraint address_id_restaurants
            references address,
    payment_id    bigint
        constraint payment_id_restaurants
            references payments
);

COMMENT ON TABLE restaurants IS 'Рестораны';
COMMENT ON COLUMN restaurants.restaurant_id IS 'Номер ресторана';
COMMENT ON COLUMN restaurants.distance IS 'Дистанция до клиента';
COMMENT ON COLUMN restaurants.name IS 'Название ресторана';
COMMENT ON COLUMN restaurants.address_id IS 'Номер адреса';
COMMENT ON COLUMN restaurants.payment_id IS 'Номер оплаты';

create table if not exists restaurant_menu_items
(
    restaurant_menu_item_id bigint generated by default as identity
        primary key,
    description             varchar(255) not null,
    name                    varchar(255) not null,
    price                   integer      not null,
    image_id                bigint
        constraint image_id_restaurant_menu_items
            references images,
    restaurant_id           bigint
        constraint restaurant_id_restaurant_menu_items
            references restaurants
);

COMMENT ON TABLE restaurant_menu_items IS 'Пункты меню ресторанов';
COMMENT ON COLUMN restaurant_menu_items.restaurant_menu_item_id IS 'Номер пункта меню';
COMMENT ON COLUMN restaurant_menu_items.description IS 'Описание пункта меню';
COMMENT ON COLUMN restaurant_menu_items.name IS 'Название пункта меню';
COMMENT ON COLUMN restaurant_menu_items.price IS 'Цена пункта меню';
COMMENT ON COLUMN restaurant_menu_items.image_id IS 'Номер изображения';
COMMENT ON COLUMN restaurant_menu_items.restaurant_id IS 'Номер ресторана';

create table if not exists orders
(
    order_id      bigint generated by default as identity
        primary key,
    status        varchar(255),
    timestamp     timestamptz,
    courier_id    bigint
        constraint courier_id_orders
            references couriers,
    customer_id   bigint
        constraint customer_id_orders
            references customers,
    restaurant_id bigint
);

COMMENT ON TABLE orders IS 'Заказы';
COMMENT ON COLUMN orders.order_id IS 'Номер заказа';
COMMENT ON COLUMN orders.status IS 'Статус заказа';
COMMENT ON COLUMN orders.timestamp IS 'Время заказа';
COMMENT ON COLUMN orders.courier_id IS 'Номер курьера';
COMMENT ON COLUMN orders.customer_id IS 'Номер клиента';
COMMENT ON COLUMN orders.restaurant_id IS 'Номер ресторана';

create table if not exists items
(
    item_id                 bigint generated by default as identity
        primary key,
    description             varchar(255) not null,
    name                    varchar(255) not null,
    price                   integer      not null,
    quantity                integer      not null,
    image_id                bigint,
    order_id                bigint
        constraint order_id_items
            references orders,
    restaurant_menu_item_id bigint
        constraint restaurant_menu_item_id_items
            references restaurant_menu_items
);

COMMENT ON TABLE items IS 'Товары';
COMMENT ON COLUMN items.item_id IS 'Номер товара';
COMMENT ON COLUMN items.description IS 'Описание товара';
COMMENT ON COLUMN items.name IS 'Название товара';
COMMENT ON COLUMN items.price IS 'Цена товара';
COMMENT ON COLUMN items.quantity IS 'Количество товаров';
COMMENT ON COLUMN items.image_id IS 'Номер изображения';
COMMENT ON COLUMN items.order_id IS 'Номер заказа';

create table if not exists delivery
(
    delivery_id   bigint generated by default as identity
        primary key,
    status        varchar(255),
    customer_id   bigint
        constraint customer_id_delivery
            references customers,
    order_id      bigint
        constraint order_id_delivery
            references orders,
    payment_id    bigint
        constraint payment_id_delivery
            references payments,
    restaurant_id bigint
        constraint restaurant_id_delivery
            references restaurants
);

COMMENT ON TABLE delivery IS 'Доставка';
COMMENT ON COLUMN delivery.delivery_id IS 'Номер доставки';
COMMENT ON COLUMN delivery.status  IS 'Статус доставки';
COMMENT ON COLUMN delivery.customer_id IS 'Номер клиента';
COMMENT ON COLUMN delivery.order_id IS 'Номер заказа';
COMMENT ON COLUMN delivery.payment_id IS 'Номер оплаты';
COMMENT ON COLUMN delivery.restaurant_id IS 'Номер ресторана';

create schema if not exists auth;

create table if not exists auth.oauth2_registered_client
(
    id                            varchar(100)                            not null
        primary key,
    client_id                     varchar(100)                            not null,
    client_id_issued_at           timestamp     default CURRENT_TIMESTAMP not null,
    client_secret                 varchar(200)  default NULL::character varying,
    client_secret_expires_at      timestamp,
    client_name                   varchar(200)                            not null,
    client_authentication_methods varchar(1000)                           not null,
    authorization_grant_types     varchar(1000)                           not null,
    redirect_uris                 varchar(1000) default NULL::character varying,
    scopes                        varchar(1000)                           not null,
    client_settings               varchar(2000)                           not null,
    token_settings                varchar(2000)                           not null
);

alter table if exists auth.oauth2_registered_client
    owner to postgres;

create table if not exists auth.users
(
    username varchar(50)          not null
        primary key,
    password varchar(100)         not null,
    enabled  boolean default true not null
);

alter table if exists auth.users
    owner to postgres;

create table if not exists auth.authorities
(
    username  varchar(50) not null
        references auth.users,
    authority varchar(50) not null
);

alter table if exists auth.authorities
    owner to postgres;